# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# Maximum line length
Metrics/LineLength:
  Max: 160
  IgnoreCopDirectives: true

# Maximum block length
Metrics/BlockLength:
  Max: 40

# Disable the need for documentation at top of each module
Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false